name: Cursor Review
on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl https://cursor.com/install -fsS | bash
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH
      - run: cursor review
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}