name: Cursor Review
on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl https://cursor.com/install -fsS | bash
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH
      - run: |
          cursor-agent -p "You are an automated code reviewer. Focus on security issues, logic bugs, missing tests, and code style. Provide detailed feedback on the PR changes." --model gpt-4
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}