name: Cursor Review
on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -fsSL https://cursor.sh/install-cli | bash
      - run: cursor review
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}